task :default => :tu

desc "Ejecutar las pruebas unitarias  de la clase  Alimento.rb"
task :tu do
  sh "ruby -I. test/tc_alimento.rb"
end

desc "Ejecutar solo las pruebas simples"
task :simple do 
  sh "ruby -I. test/tc_alimento.rb -n /simple/"
end
